# Generated by Django 5.1.4 on 2026-04-29 03:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deletado_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deletado em')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('matricula', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Matrícula')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('numero_cnh', models.CharField(blank=True, max_length=20, verbose_name='CNH')),
                ('numero_curso_vigilante', models.CharField(blank=True, max_length=50, verbose_name='N° curso vigilante')),
                ('validade_curso', models.DateField(blank=True, null=True, verbose_name='Validade do curso')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('afastado', 'Afastado')], db_index=True, default='ativo', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Ronda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deletado_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deletado em')),
                ('data_hora_inicio', models.DateTimeField(db_index=True, verbose_name='Início')),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('turno', models.CharField(blank=True, choices=[('manha', 'Manhã (06h-12h)'), ('tarde', 'Tarde (12h-18h)'), ('noite', 'Noite (18h-00h)'), ('madrugada', 'Madrugada (00h-06h)')], db_index=True, max_length=15, verbose_name='Turno')),
                ('status', models.CharField(choices=[('programada', 'Programada'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('nao_realizada', 'Não realizada'), ('ocorrencia', 'Com ocorrência')], db_index=True, default='programada', max_length=20, verbose_name='Status')),
                ('teve_ocorrencia', models.BooleanField(db_index=True, default=False, verbose_name='Houve ocorrência?')),
                ('descricao_ocorrencia', models.TextField(blank=True, verbose_name='Descrição da ocorrência')),
                ('houve_acionamento_policia', models.BooleanField(default=False, verbose_name='Polícia acionada?')),
                ('numero_bo', models.CharField(blank=True, max_length=50, verbose_name='Número do B.O.')),
                ('latitude_chegada', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude chegada')),
                ('longitude_chegada', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude chegada')),
                ('avaliacao', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação (1-5)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rondas', to='rondas.agente', verbose_name='Agente responsável')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rondas', to='clientes.cliente', verbose_name='Cliente')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rondas', to='contratos.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Ronda',
                'verbose_name_plural': 'Rondas',
                'ordering': ['-data_hora_inicio'],
                'indexes': [models.Index(fields=['status', 'data_hora_inicio'], name='rondas_rond_status_ffc34e_idx'), models.Index(fields=['cliente', 'status'], name='rondas_rond_cliente_d2ca76_idx'), models.Index(fields=['agente', 'data_hora_inicio'], name='rondas_rond_agente__5da82e_idx'), models.Index(fields=['teve_ocorrencia'], name='rondas_rond_teve_oc_f686b6_idx')],
            },
        ),
    ]
