# Generated by Django 5.1.4 on 2026-04-29 03:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='E-mail')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('perfil', models.CharField(choices=[('admin', 'Administrador'), ('gerente', 'Gerente'), ('operador', 'Operador'), ('financeiro', 'Financeiro')], db_index=True, default='operador', max_length=20, verbose_name='Perfil')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='Avatar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True, verbose_name='Último acesso')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LogAtividade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acao', models.CharField(choices=[('criacao', 'Criação'), ('edicao', 'Edição'), ('exclusao', 'Exclusão'), ('restauracao', 'Restauração'), ('pagamento', 'Pagamento'), ('emissao_boleto', 'Emissão de boleto'), ('cancelamento', 'Cancelamento'), ('login', 'Login'), ('logout', 'Logout')], db_index=True, max_length=30, verbose_name='Ação')),
                ('tabela', models.CharField(db_index=True, max_length=100, verbose_name='Tabela')),
                ('registro_id', models.CharField(blank=True, db_index=True, max_length=36, verbose_name='ID do registro')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('dados_anteriores', models.JSONField(blank=True, null=True, verbose_name='Dados anteriores')),
                ('dados_novos', models.JSONField(blank=True, null=True, verbose_name='Dados novos')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de atividade',
                'verbose_name_plural': 'Logs de atividade',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tabela', 'registro_id'], name='core_logati_tabela_6cf194_idx'), models.Index(fields=['usuario', 'acao'], name='core_logati_usuario_54d875_idx')],
            },
        ),
    ]
