# Generated by Django 5.1.4 on 2026-04-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='admin', help_text='Usado para login. Apenas letras, números e @/./+/-/_', max_length=50, unique=True, verbose_name='Nome de usuário'),
            preserve_default=False,
        ),
    ]
