# Generated by Django 5.1.4 on 2026-05-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Minha Empresa', max_length=200, verbose_name='Nome da empresa')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30, verbose_name='Inscrição estadual')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('site', models.URLField(blank=True, verbose_name='Site')),
                ('logradouro', models.CharField(blank=True, max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('logo', models.ImageField(blank=True, help_text='Aparece no cabeçalho do recibo e no sistema. Recomendado: PNG fundo transparente, mín. 200×80 px.', null=True, upload_to='empresa/logos/', verbose_name='Logo')),
                ('rodape_recibo', models.CharField(blank=True, help_text='Texto exibido no rodapé do recibo de pagamento.', max_length=300, verbose_name='Rodapé do recibo')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresa',
            },
        ),
    ]
