# Generated by Django 5.1.4 on 2026-04-29 03:10

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deletado_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deletado em')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome do serviço')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('ronda_residencial', 'Ronda residencial'), ('ronda_comercial', 'Ronda comercial'), ('monitoramento', 'Monitoramento eletrônico'), ('seguranca_evento', 'Segurança em evento'), ('portaria', 'Portaria / Recepção'), ('outros', 'Outros')], db_index=True, default='ronda_residencial', max_length=30, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor mensal (R$)')),
                ('duracao_minima_meses', models.PositiveSmallIntegerField(default=12, help_text='Quantidade mínima de meses do contrato.', verbose_name='Duração mínima (meses)')),
                ('frequencia_rondas_semana', models.PositiveSmallIntegerField(default=0, help_text='Quantas rondas por semana estão inclusas no plano. 0 = não se aplica.', verbose_name='Rondas por semana')),
                ('horario_inicio', models.TimeField(blank=True, help_text='Horário de início das rondas previstas no plano.', null=True, verbose_name='Horário início')),
                ('horario_fim', models.TimeField(blank=True, null=True, verbose_name='Horário fim')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveSmallIntegerField(default=0, help_text='Ordena a exibição no cadastro de contratos.', verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['ordem', 'nome'],
                'indexes': [models.Index(fields=['tipo', 'ativo'], name='servicos_se_tipo_fe3fa1_idx')],
            },
        ),
    ]
