# Generated by Django 5.1.4 on 2026-04-29 03:10

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deletado_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deletado em')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, verbose_name='Nome fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$', 'CNPJ inválido.')], verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30, verbose_name='Inscrição estadual')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=30, verbose_name='Inscrição municipal')),
                ('categoria', models.CharField(choices=[('equipamentos', 'Equipamentos de segurança'), ('uniformes', 'Uniformes e EPIs'), ('veiculos', 'Veículos e manutenção'), ('tecnologia', 'Tecnologia e TI'), ('servicos_gerais', 'Serviços gerais'), ('recursos_humanos', 'Recursos humanos / Terceiros'), ('outros', 'Outros')], db_index=True, default='outros', max_length=30, verbose_name='Categoria')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('bloqueado', 'Bloqueado')], db_index=True, default='ativo', max_length=20, verbose_name='Status')),
                ('contato_nome', models.CharField(blank=True, max_length=200, verbose_name='Nome do contato')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('site', models.URLField(blank=True, verbose_name='Site')),
                ('cep', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{3}$', 'CEP inválido.')], verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('banco', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('agencia', models.CharField(blank=True, max_length=10, verbose_name='Agência')),
                ('conta', models.CharField(blank=True, max_length=20, verbose_name='Conta')),
                ('tipo_conta', models.CharField(blank=True, choices=[('corrente', 'Corrente'), ('poupanca', 'Poupança')], max_length=20, verbose_name='Tipo de conta')),
                ('chave_pix', models.CharField(blank=True, max_length=150, verbose_name='Chave PIX')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['razao_social'],
                'indexes': [models.Index(fields=['categoria', 'status'], name='fornecedore_categor_3ad63e_idx')],
            },
        ),
    ]
