# Generated by Django 5.1.4 on 2026-04-29 03:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deletado_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deletado em')),
                ('numero_parcela', models.PositiveSmallIntegerField(verbose_name='Número da parcela')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor (R$)')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor pago (R$)')),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Juros (R$)')),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Multa (R$)')),
                ('desconto_pagamento', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Desconto no pagamento (R$)')),
                ('data_vencimento', models.DateField(db_index=True, verbose_name='Data de vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada'), ('estornada', 'Estornada')], db_index=True, default='pendente', max_length=20, verbose_name='Status')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('boleto', 'Boleto bancário'), ('pix', 'PIX'), ('cartao_credito', 'Cartão de crédito'), ('cartao_debito', 'Cartão de débito'), ('transferencia', 'Transferência bancária'), ('dinheiro', 'Dinheiro'), ('cheque', 'Cheque')], max_length=20, verbose_name='Forma de pagamento')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/%Y/%m/', verbose_name='Comprovante')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensalidades', to='contratos.contrato', verbose_name='Contrato')),
                ('recebido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensalidades_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Recebido por')),
            ],
            options={
                'verbose_name': 'Mensalidade',
                'verbose_name_plural': 'Mensalidades',
                'ordering': ['data_vencimento'],
                'indexes': [models.Index(fields=['status', 'data_vencimento'], name='mensalidade_status_00ca1c_idx'), models.Index(fields=['contrato', 'status'], name='mensalidade_contrat_8c1a02_idx')],
                'unique_together': {('contrato', 'numero_parcela')},
            },
        ),
    ]
