# Generated by Django 5.1.4 on 2026-04-29 03:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deletado_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deletado em')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de término')),
                ('numero_mensalidades', models.PositiveSmallIntegerField(help_text='Quantidade total de parcelas a serem geradas.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Número de mensalidades')),
                ('valor_mensal', models.DecimalField(decimal_places=2, help_text='Valor negociado (pode diferir do valor padrão do serviço).', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor mensal (R$)')),
                ('dia_vencimento', models.PositiveSmallIntegerField(default=10, help_text='Dia do mês para vencimento das mensalidades (1-28).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='Dia de vencimento')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Desconto (R$)')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado'), ('encerrado', 'Encerrado')], db_index=True, default='rascunho', max_length=20, verbose_name='Status')),
                ('numero_contrato', models.CharField(blank=True, help_text='Gerado automaticamente se deixado em branco.', max_length=30, unique=True, verbose_name='Número do contrato')),
                ('mensalidades_geradas', models.BooleanField(default=False, help_text='Indica se as mensalidades já foram criadas para este contrato.', verbose_name='Mensalidades geradas?')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
