# Generated by Django 5.1.4 on 2026-04-29 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        ('servicos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='servicos.servico', verbose_name='Serviço'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['status', 'data_fim'], name='contratos_c_status_fb75e3_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['cliente', 'status'], name='contratos_c_cliente_aaeac0_idx'),
        ),
    ]
