# Generated by Django 5.1.4 on 2026-04-29 03:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deletado_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deletado em')),
                ('banco', models.CharField(choices=[('asaas', 'Asaas'), ('efi', 'Efí Bank / Gerencianet'), ('inter', 'Banco Inter'), ('itau', 'Itaú'), ('bradesco', 'Bradesco'), ('sicoob', 'Sicoob')], db_index=True, max_length=20, verbose_name='Banco')),
                ('nosso_numero', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Nosso número')),
                ('linha_digitavel', models.CharField(blank=True, max_length=200, verbose_name='Linha digitável')),
                ('codigo_barras', models.CharField(blank=True, max_length=200, verbose_name='Código de barras')),
                ('url_pdf', models.URLField(blank=True, max_length=500, verbose_name='URL do PDF')),
                ('url_pagamento', models.URLField(blank=True, help_text='Link para pagamento online (Asaas, Efí etc.).', max_length=500, verbose_name='Link de pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('emitido', 'Emitido'), ('registrado', 'Registrado no banco'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado'), ('erro', 'Erro na emissão')], db_index=True, default='pendente', max_length=20, verbose_name='Status')),
                ('emitido_em', models.DateTimeField(blank=True, null=True, verbose_name='Emitido em')),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('id_externo', models.CharField(blank=True, db_index=True, help_text='Identificador retornado pela API da instituição financeira.', max_length=100, verbose_name='ID externo (banco)')),
                ('resposta_emissao', models.JSONField(blank=True, help_text='Payload completo retornado pela API na emissão.', null=True, verbose_name='Resposta da emissão (JSON)')),
                ('resposta_webhook', models.JSONField(blank=True, help_text='Último payload de webhook recebido do banco.', null=True, verbose_name='Último webhook recebido (JSON)')),
                ('tentativas', models.PositiveSmallIntegerField(default=0, verbose_name='Tentativas de emissão')),
                ('erro_mensagem', models.TextField(blank=True, verbose_name='Mensagem de erro')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='WebhookBoleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=20, verbose_name='Banco')),
                ('evento', models.CharField(db_index=True, max_length=100, verbose_name='Evento')),
                ('payload', models.JSONField(verbose_name='Payload')),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origem')),
                ('processado', models.BooleanField(db_index=True, default=False, verbose_name='Processado?')),
                ('erro', models.TextField(blank=True, verbose_name='Erro ao processar')),
                ('recebido_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Recebido em')),
            ],
            options={
                'verbose_name': 'Webhook de boleto',
                'verbose_name_plural': 'Webhooks de boletos',
                'ordering': ['-recebido_em'],
            },
        ),
    ]
