# Generated by Django 5.1.4 on 2026-04-29 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boletos', '0001_initial'),
        ('mensalidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='mensalidade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='boleto', to='mensalidades.mensalidade', verbose_name='Mensalidade'),
        ),
        migrations.AddField(
            model_name='webhookboleto',
            name='boleto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to='boletos.boleto', verbose_name='Boleto'),
        ),
        migrations.AddIndex(
            model_name='boleto',
            index=models.Index(fields=['status', 'vencimento'], name='boletos_bol_status_ff4f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='boleto',
            index=models.Index(fields=['banco', 'nosso_numero'], name='boletos_bol_banco_3b463a_idx'),
        ),
    ]
